# Numpy (Numerical Python)

C언어 기반 파이썬 라이브러리.

고성능의 수치계산 및 과학 계산을 위한 라이브러리 +
수치 연산을 수행하는 선형 대수 (Linear algebra)라이브러리

List의 확장판 (데이터 연산, 통계 분석) 느낌

다차원 배열을 처리하는데 필요한 여러 유용한 기능을 제공 >
데이터 분석을 할 때 사용하는 라이브러리인 pandas와 matplotlib의 기반으로 사용되기도 함 

단순하게 [다차원 배열로 표현]한다라고 이해하면 좋음

모든 배열의 값이 기본적으로 같은 자료형(타입)이어야 함

Numpy에서는 각 차원(Dimension)을 축(axis)으로 표현

핵심적인 기능 : ndarry 객체 

ndarray 객체는 동일한 자료형의 n-차원 배열을 모아주는 역할

배열의 차원 : rank 

각 차원의 크기를 tuple로 표시 : shape

ex) 2행 3열인 경우 : 2차원 배열에서 rank는 2, shape (2,3)

numpy 배열을 생성하는 방법
1. python list
2. numpy 제공 함수



In [ ]:
import numpy as np
import matplotlib.pyplot as plt

list : 하나의 리스트 안에 숫자, 문자 등 다양한 자료형이 섞여있는게 가능

numpy : 항상 같은 타입의 데이터틀만 들어갈 수 있음

# Part 1. Numpy ndarray

Numpy의 핵심 기능 : ndarray

ndarray : 다차원의 배열 객체 / 파이썬에서 할 수 있는 대규모 데이터 집합을 담을 수 있는 빠르고 유연한 자료구조

용어 정리 

scalar : 상수 값 (10, 3.14159265, 'korea')

vector(1차원) : [10, 20, 30]

matrix(2차원) : [ [10, 20, 30], [100, 200, 300] ] 2 * 3

3차원 : [ [ [10, 20, 30], [100, 200, 300], [ [ 10, 20, 30 ], [ 100, 200, 300 ] ] ] 2* 3

In [ ]:
data1 = [1,2,3,4]
data1

In [ ]:
data2 = [1,2,3,3.5,4]
data2

# numpy를 이용해서 array 정의하기

# 1. 위에서 만든 python list를 이용

arr1 = np.array(data1)
print(arr1)

arr2 = np.array(data2)
arr2

# python list 넣어서 만들기 

a = np.array([1,2,3])
print(a, type(a))

data = [1,2,3,4,5]
array = np.array(data)
print(array, type(array))

# 2. arange 사용 

arr3 = np.arange(1,11) # 1~(11-1) 까지
arr3

# 1 ~ 10까지 2씩 증가한 만큼의 숫자를 배열에 담기

arr4 = np.arange(1,11,2)
arr4

In [ ]:
# 3. random

arr5 = np.random.randint(1,11, size=5) # 1 ~ 10까지의 숫자를 랜덤하게 5개 뽑기 
arr5

In [ ]:
# 1 ~ 10까지의 숫자를 랜덤하게 3행 2열로 뽑기

arr6 = np.random.randint(1,11,size=(3,2))
arr6

# np.random 관련함수 

- np.random.rand()
- np.random.randint()
- np.random.randn()
- np.random.choice()

In [ ]:
np.random.rand(5) # 0~1 사이의 랜덤한 실수값 반환 (5개)

In [ ]:
np.random.rand(2,3) # 0 ~ 1 사이의 랜덤한 실수값을 2행 3열로 반환

In [ ]:
np.random.randint(10) # 0 ~ (10-1) 까지의 랜덤한 정수값 반환

In [ ]:
np.random.randn(5) # 표준 정규분호 값 5개 반환 (평균 0, 편차 1)

In [ ]:
np.random.choice([1,2,3,4,5]) # 배열 안의 값 중 랜덤한거 하나 뽑아서 반환

In [ ]:
# 1 ~ 10 사이의 수를 랜덤하게 5개 뽑아서 반환
np.random.randint(11,size=5)
np.random.choice(np.arange(1,10),5)

In [ ]:
# List와 비교 
l = [1,2,3]
a = np.array([1,2,3])
print(l)
print(a)

In [ ]:
# list 반복문
for item in l:
  print(item)

print('-'*3)

# numpy 반복문 
for item in a:
  print(item)

In [ ]:
# list에서 append
l.append(4) # 뒤에 4 추가
print(l)

# numpy에서 append 불가능
# a = a.append(4)
# print(a)

In [ ]:
# numpy에서 append >> np.append으로 대상 선정 후 가능
a = np.append(a,4)
print(a)

In [ ]:
# list에서의 덧셈
l = l + [5] # 뒤에 5 추가
print(l)

# numpy에서의 덧셈 
a = a + np.array([5]) # 각 요소에 + 5
print(a)

In [ ]:
# list의 모든 요소를 2배로 만들기
l = [1,2,3]
l2 = []
for item in l:
  l2.append(item*2)
print(l2)

In [ ]:
l = l * 2 # 이 곱셈은 요소가 몇번 반복되는지
print(l)

In [ ]:
# ndarray의 모든 요소를 2배로 만들기
a = np.array(l)
a = a * 2
print(a)

In [ ]:
data = np.random.randn(1,3)
print(data)

# 산술 연산
dataMul = data * 10
print(dataMul)

dataAdd = data + data
print(dataAdd)

# Part2. 배열 

Numpy 배열은 모두 같은 자료형(유형)의 값이며, 음수가 아닌 정수의 튜플로 인덱싱

배열의 shape은 각 차원별 배열 크기의 tuple

중첩된 파이썬 리스트로부터 numpy 배열을 초기화 할 수 있고, 대괄호를 사용해서 요소로 접근 가능 O



# Array 연산

기본적으로 numpy에서 연산을 하는 경우

서로 크기가 같은 array끼리 연산을 진행

같은 위치에 있는 요소들끼리 연산을 진행 

# Array BroadCasting

브로드캐스팅(BroadCasting)은 모양이 다른 배열들 간의 연산이 어떤 조건이 갖춰졌을 때 (만족했을 때) 가능해지도록 배열을 자동적으로 변환하는 것 

=> 서로 크기가 다른 array들의 연산이 가능 

# Part3. 배열 indexing(색인)과 slicing(슬라이싱)


In [ ]:
# basic
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# indexing
# a에서 5 출력 
print(a[5])

In [ ]:
# np.arange() 함수는 파라미터로 받는 값 만큼 1씩 증가하는 1차원의 array를 만듦
# 이 때 하나의 파라미터만 입력하면 0 ~ (입력한 값 - 1) 만큼의 크기를 가짐
k = np.arange(10)
print(k)
# 두개의 파라미터를 넣으면 시작값 ~ (끝값 -1) 만큼의 크기를 가짐
kk = np.arange(3,10)
print(kk)

In [ ]:
# slicing
print(a)
# a에서 5,6,7값 출력
print(a[5:8])

# 맨 뒤에 있는 요소의 값
print(a[-1])

# 시작부터 7번째까지 2개씩 띄워서 출력
print(a[0:8:2])
print(a[:8:2])

# [5 6 7] 자리를 10으로 채우기 
a[5:8] = 10
print(a)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
9
[0 2 4 6]
[0 2 4 6]
[ 0  1  2  3  4 10 10 10  8  9]


In [ ]:
ex = [[1,2,3],[4,5,6],[7,8,9]]
exx = np.array(ex)
print(exx.shape)

# 콤마를 이용한 slicing
# 1행에 대한 값만 추출
print(exx[:1,])

# 1열에 대한 값만 추출
print(exx[:,1])

(3, 3)
[[1 2 3]]
[2 5 8]


# Indexing과 Slicing의 차이 

indexing을 사용하면 항상 랭크(차원) 감소 

slicing을 사용하면 랭크(차원) 유지

In [ ]:
b = np.arange(1,13)
b = b.reshape(3,4) # 모양을 다시 잡아준다
print(b)
print(b.shape)
print(b.ndim) # 몇차원인지 보여주는

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2


In [ ]:
# 몇차원인지는 중괄호의 갯수로 파악하거나 ndim 이용
# b = np.arange(1,13).reshape(3,4) # 1~12까지를 3행4열로
b = np.arange(1,13).reshape(3,2,2) # 3차원으로 2행 2열
print(b)
print(b.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3


In [ ]:
indexing = b[1]
slicing = b[1:2]
print(indexing,indexing.shape, indexing.ndim)
print()
print(slicing, slicing.shape, slicing.ndim)

# indexing과 slicing을 함께 사용해도 마찬가지로
# indexing의 갯수만큼 랭크(차원) 감소 ...

[[5 6]
 [7 8]] (2, 2) 2

[[[5 6]
  [7 8]]] (1, 2, 2) 3


In [ ]:
# 요소의 갯수만큼 크기를 지정해줘야 함
print(np.arange(1,13).reshape(3,4))
# print(np.arange(1,13).reshape(3,3)) # 그릇이 너무 작아서 만들어지지않음.

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# array 수정

arr = np.array([11,22,33,44,55])
print(arr)

# 0번째 인덱스의 값을 10으로 변경
arr[0] = 10
print(arr)

# 1,2 번째 인덱스의 값을 222, 333으로 변경
arr[1:3] = [222,333]
print(arr)

# 3,4 번째 인덱스의 값에 2를 더하기
arr[3:5] += 2
print(arr)

[11 22 33 44 55]
[10 22 33 44 55]
[ 10 222 333  44  55]
[ 10 222 333  46  57]


In [ ]:
arr = np.array([110,222,337,420,155,978,200,53,178])
print(arr)

# arr에서 200보다 큰 데이터를 기존값에 2를 더한 값으로 수정
for i in range(0,arr.shape[0]):
  if (arr[i] > 200):
    arr[i] += 2

print(arr)

# 다른 방법으로는

[110 222 337 420 155 978 200  53 178]
[110 224 339 422 155 980 200  53 178]


In [ ]:
arr = np.array([110,222,337,420,155,978,200,53,178])
print(arr)

# 인덱스 안에서 조건을 걸 수 있음

arr[arr > 200] += 2
print(arr)

[110 222 337 420 155 978 200  53 178]
[110 224 339 422 155 980 200  53 178]


In [ ]:
arr = np.array([11,3,24,7,5,18,2])
print(arr)

# arr에서 10보다 작은 데이터에 대해 기존값에 10을 곱한 값으로 수정
arr[arr<10] *= 10
print(arr)

[11  3 24  7  5 18  2]
[11 30 24 70 50 18 20]


In [ ]:
# array 삭제 
arr = np.array([11,22,33,44,55])
print(arr)

# 0번째, 2번째 인덱스 값 삭제 
# np.delete(array, [index])
arr = np.delete(arr,[0,2])
print(arr)

# array 인덱스 추출
# np.where(조건)

# arr의 각 요소의 값이 100보다 작은 index 추출
np.where(arr < 100)
# index가 정리되어서 나타나는걸 확인 할 수 있음

[11 22 33 44 55]
[22 44 55]


(array([0, 1, 2]),)

In [ ]:
arr = np.array([11,130,370,114,55,94,200,30,190,187])
print(arr)

# np.where 의 기능 살펴보고
# arr의 각 요소가 100 이상이면 A, 아니면 B 를 출력 

np.where(arr >= 100,'A','B')

[ 11 130 370 114  55  94 200  30 190 187]


array(['B', 'A', 'A', 'A', 'B', 'B', 'A', 'B', 'A', 'A'], dtype='<U1')

# Numpy 함수

# 하나의 array에 적용 (단항 유니버셜 함수)

유니버셜 함수 : ndarray안에 있는 데이터의 요소별로 연산을 수행해주는 함수

In [ ]:
ar1 = np.random.randn(5,3)
ar1

array([[-0.13290645, -0.65332328,  0.71257516],
       [ 0.64712929,  0.2359071 , -2.01328057],
       [ 1.18903996,  1.04098968,  1.03973726],
       [ 0.51762404, -0.47164835, -0.54681974],
       [-0.45662614, -0.76134008,  0.03511533]])

In [ ]:
# 각 요소의 절대값 
np.abs(ar1)

array([[0.13290645, 0.65332328, 0.71257516],
       [0.64712929, 0.2359071 , 2.01328057],
       [1.18903996, 1.04098968, 1.03973726],
       [0.51762404, 0.47164835, 0.54681974],
       [0.45662614, 0.76134008, 0.03511533]])

In [ ]:
# 각 요소의 제곱근 계산 (== array ** 0.5)
np.sqrt(ar1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


array([[       nan,        nan, 0.84414167],
       [0.80444347, 0.48570269,        nan],
       [1.09043109, 1.02028902, 1.01967508],
       [0.71946094,        nan,        nan],
       [       nan,        nan, 0.18739084]])

In [ ]:
# 각 요소의 제곱 계산 
np.square(ar1)

array([[1.76641251e-02, 4.26831305e-01, 5.07763354e-01],
       [4.18776320e-01, 5.56521592e-02, 4.05329865e+00],
       [1.41381604e+00, 1.08365952e+00, 1.08105357e+00],
       [2.67934651e-01, 2.22452161e-01, 2.99011833e-01],
       [2.08507436e-01, 5.79638723e-01, 1.23308621e-03]])

In [ ]:
# 각 요소를 무리수 e의 지수로 삼은 값을 계산 
np.exp(ar1)

array([[0.87554699, 0.52031375, 2.03923585],
       [1.91004976, 1.26605669, 0.13354984],
       [3.283927  , 2.83201843, 2.82847376],
       [1.67803597, 0.6239729 , 0.57878758],
       [0.6334171 , 0.46704013, 1.03573915]])

In [ ]:
# 각 요소를 자연로그, 상용로그, 아래가 2인 로그를 씌운 값 계산
print(np.log(ar1))
print()
print(np.log10(ar1))
print()
print(np.log2(ar1))

[[        nan         nan -0.33886989]
 [-0.43520917 -1.4443172          nan]
 [ 0.17314623  0.04017188  0.03896805]
 [-0.65850608         nan         nan]
 [        nan         nan -3.34911757]]

[[        nan         nan -0.14716932]
 [-0.18900894 -0.62725899         nan]
 [ 0.07519645  0.01744643  0.01692361]
 [-0.28598556         nan         nan]
 [        nan         nan -1.45450328]]

[[        nan         nan -0.48888591]
 [-0.62787411 -2.08370926         nan]
 [ 0.2497972   0.05795577  0.05621901]
 [-0.95002346         nan         nan]
 [        nan         nan -4.83175531]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in log10
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in log2
  


In [ ]:
# 각 요소의 부호 계산하기 (+ : 1, - : -1, 0 : 0)
np.sign(ar1)

array([[-1., -1.,  1.],
       [ 1.,  1., -1.],
       [ 1.,  1.,  1.],
       [ 1., -1., -1.],
       [-1., -1.,  1.]])

In [ ]:
# 각 요소의 소수 첫번째 자리에서 올림한 값 계산
np.ceil(ar1)

array([[-0., -0.,  1.],
       [ 1.,  1., -2.],
       [ 2.,  2.,  2.],
       [ 1., -0., -0.],
       [-0., -0.,  1.]])

In [ ]:
# 각 요소의 소수 첫번째 자리에서 내림한 값 계산
np.floor(ar1)

array([[-1., -1.,  0.],
       [ 0.,  0., -3.],
       [ 1.,  1.,  1.],
       [ 0., -1., -1.],
       [-1., -1.,  0.]])

In [ ]:
# 각 요소가 nan인 경우 True, 아닌 경우 False를 변환
np.isnan(ar1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
np.isnan(np.log(ar1))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


array([[ True,  True, False],
       [False, False,  True],
       [False, False, False],
       [False,  True,  True],
       [ True,  True, False]])

In [ ]:
# 각 요소가 무한대인 경우 True, 아닌 경우 False 반환
np.isinf(ar1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
# 각 요소에 대해 삼각함수 값을 계산하기 (cos, cosh, sin, sinh, tan, tanh)
# ~h : 쌍곡선 함수
# 쌍곡선 : 고정된 두 초첨으로부터 거리가 일정한 점들에 의해 나타나는 곡선
np.cos(ar1)

array([[ 0.99118093,  0.7940682 ,  0.75668079],
       [ 0.79781783,  0.97230273, -0.42818577],
       [ 0.37255097,  0.5053665 ,  0.50644683],
       [ 0.86899729,  0.89082056,  0.85418249],
       [ 0.89754521,  0.72391215,  0.99938352]])

두 개의 array에 적용 (이항 유니버셜함수)

In [ ]:
ar1

array([[-0.13290645, -0.65332328,  0.71257516],
       [ 0.64712929,  0.2359071 , -2.01328057],
       [ 1.18903996,  1.04098968,  1.03973726],
       [ 0.51762404, -0.47164835, -0.54681974],
       [-0.45662614, -0.76134008,  0.03511533]])

In [ ]:
ar2 = np.random.randn(5,3)
ar2

array([[ 1.15372978,  0.75238942, -1.18435733],
       [-0.49858544, -0.54324045,  1.26383338],
       [ 0.29763871, -2.03288745,  1.46035275],
       [ 0.20820363, -0.96855161,  0.95927892],
       [ 1.70024646, -0.33801798, -0.38949231]])

In [ ]:
# 두 개의 array에 대해 동일한 위치 요소끼리
# 연산 값을 계산하기(add, subtract, multiply, divide)
np.multiply(ar1, ar2)

array([[-0.15333813, -0.49155352, -0.84394361],
       [-0.32264924, -0.12815428, -2.54445118],
       [ 0.35390432, -2.11621487,  1.51838316],
       [ 0.1077712 ,  0.45681576, -0.52455265],
       [-0.77637699,  0.25734663, -0.01367715]])

In [ ]:
# 두 개의 array에 대해 동일한 위치의 요소끼리 비교해서 최대값 or 최소값 계산 (maximum, minimum)
np.maximum(ar1,ar2)

array([[ 1.15372978,  0.75238942,  0.71257516],
       [ 0.64712929,  0.2359071 ,  1.26383338],
       [ 1.18903996,  1.04098968,  1.46035275],
       [ 0.51762404, -0.47164835,  0.95927892],
       [ 1.70024646, -0.33801798,  0.03511533]])

# 통계 함수

통계 함수를 통해 array의 합이나 평균 등을 구할 때

추가로 'axis'라는 파라미터에 대한 값을 지정하여 

열 또는 행의 합 또는 평균 등을 구할 수 있음 

In [ ]:
# 전체 요소의 합을 계산 
np.sum(ar1)

0.3821732069956184

In [ ]:
# 열 간의 합을 계산 
np.sum(ar1,axis=0)

array([ 1.7642607 , -0.60941492, -0.77267257])

In [ ]:
# 행 간의 합을 계산
np.sum(ar1,axis=1)

array([-0.07365457, -1.13024418,  3.26976691, -0.50084405, -1.1828509 ])

In [ ]:
# 전체 요소의 평균
# print(np.average(ar1))
np.mean(ar1)

0.025478213799707893
0.025478213799707893


In [ ]:
# 전체 요소의 표준편차, 분산, 최소값, 최대값 (std, var, min, max)
np.std(ar1)

0.841726631629049

In [ ]:
# 전체 요소의 최소값, 최대값이 위치한 인덱스를 반환 (argmin, argmax)
np.argmin(ar1)

5

In [ ]:
# 맨 처음 요소부터 각 요소까지의 누적합 or 누적곱을 계산 (cumsum, sumprod)
np.cumsum(ar1)

array([-0.13290645, -0.78622973, -0.07365457,  0.57347472,  0.80938182,
       -1.20389875, -0.01485879,  1.02613089,  2.06586815,  2.5834922 ,
        2.11184385,  1.56502411,  1.10839796,  0.34705788,  0.38217321])

In [ ]:
# 사분위수

# 0.25 : 1 사분위수 / 0.5 : 사분위수(중앙값) / 0.75 : 3 사분위수
np.quantile(ar1, [0.25, 0.5, 0.75])

array([-0.50923404,  0.03511533,  0.67985222])

기타함수

In [ ]:
# 전체 요소에 대해서 오름차순 정렬
np.sort(ar1)

array([[-0.65332328, -0.13290645,  0.71257516],
       [-2.01328057,  0.2359071 ,  0.64712929],
       [ 1.03973726,  1.04098968,  1.18903996],
       [-0.54681974, -0.47164835,  0.51762404],
       [-0.76134008, -0.45662614,  0.03511533]])

In [ ]:
# 행 방향으로 오름차순 정렬
np.sort(ar1,axis=0)

array([[-0.45662614, -0.76134008, -2.01328057],
       [-0.13290645, -0.65332328, -0.54681974],
       [ 0.51762404, -0.47164835,  0.03511533],
       [ 0.64712929,  0.2359071 ,  0.71257516],
       [ 1.18903996,  1.04098968,  1.03973726]])

In [ ]:
# zip 함수
# 각 객체를 파라미터로 받고, 그 요소들을 tuple의 형태로 반환
numbers = [1, 2, 3]
letters = ['A','B','C']

for pair in zip(numbers,letters):
  print(pair)

(1, 'A')
(2, 'B')
(3, 'C')


In [ ]:
# 문자열 "12345", "ABCDE","abcde"를 묶어서 출력하기
a = "12345"
b = "ABCDE"
c = "abcde"

for pair in zip(a,b,c):
  print(pair)

for number, upper, lower in zip('12345','ABCDE','abcde'):
  print(number,upper,lower)

('1', 'A', 'a')
('2', 'B', 'b')
('3', 'C', 'c')
('4', 'D', 'd')
('5', 'E', 'e')
1 A a
2 B b
3 C c
4 D d
5 E e
