# 인덱싱(indexing)

Python의 list / Numpy Array의 인덱싱 방법과 비슷

0부터 시작, 마지막 인덱스 -1

인덱스에 해당하는 범위를 지정하여 여러개의 요소를 슬라이싱(slicing) 추출도 가능

In [ ]:
# 텐서플로 불러오기
import tensorflow as tf

In [ ]:
# 1차원 벡터의 인덱싱

# 벡터 정의하기
vec = tf.constant([10,20,30,40,50])
print(vec)

# 0번째 요소의 스칼라값 출력
print(vec[0])
# 마지막 요소의 스칼라값 출력
print(vec[-1])
print(vec[4])
# 0~2번째까지 해당하는 요소 모두 출력
print(vec[:3])
print(vec[0:3])

tf.Tensor([10 20 30 40 50], shape=(5,), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(50, shape=(), dtype=int32)
tf.Tensor(50, shape=(), dtype=int32)
tf.Tensor([10 20 30], shape=(3,), dtype=int32)
tf.Tensor([10 20 30], shape=(3,), dtype=int32)


In [ ]:
# 2차원 행렬(matrix) 텐서
# 행방향 인덱스와 열방향 인덱스를 지정하는 방식

# (2행,4열) 크기의 랭크-2 텐서 정의
matrix = tf.constant([[1,2,3,4],
                     [5,6,7,8]])
print(matrix)
print(tf.rank(matrix))
# [0행,2열]
print(matrix[0,2])
# [0행, 모든 열]
print(matrix[0, :])
# [모든 행, 1열]
print(matrix[:,1])
# [모든 행, 모든 열]
print(matrix)
print(matrix[:,:])

tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([2 6], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)


In [ ]:
# 랭크-3 텐서

# 랭크-3 텐서 이상(고차원 텐서)의 인덱싱은
# 2차원 행렬텐서(Matrix)의 개념을 확장하는 느낌

# (3,3,4) 크기의 텐서를 만들기 (1부터 시작)
tensor = tf.constant([
                      [[1,2,3,4],
                       [5,6,7,8],
                       [9,10,11,12]],
                      
                      [[13,14,15,16],
                       [17,18,19,20],
                       [21,22,23,24]],
                      
                      [[25,26,27,28],
                       [29,30,31,32],
                       [33,34,35,36]]
                      ])
tensor
# 0번째의 모든행, 모든열
print(tensor[0, :, :])
# 1번째의 1번째 행까지, 2번째 열까지
print(tensor[1,:2, :3])
# 0~1번째의 2번째 행까지, 2~3번째 열까지
print(tensor[:2, :3, 2:4])

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[13 14 15]
 [17 18 19]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[[ 3  4]
  [ 7  8]
  [11 12]]

 [[15 16]
  [19 20]
  [23 24]]], shape=(2, 3, 2), dtype=int32)


# 형태변환(tf.reshape)

Numpy의 reshape과 상당부분 유사함

In [ ]:
import tensorflow as tf

# 랭크-1텐서 만들기 - 숫자 1~24까지 24개의 요소를 갖도록
tensor = tf.constant(range(1,25))   # 1이상 25미만
print(tensor)
# 범위 안에 있는 숫자를 순차적으로 배열로 만들어 줌

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,), dtype=int32)


In [ ]:
# 벡터(Vector) : (24, ) 형태
# 행렬(Matrix) : (4, 6) 형태로 rshape

tensor1 = tf.reshape(tensor, [4,6]) # 변환 전과 후의 원소 개수는 동일하게
print(tensor1)

tf.Tensor(
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]], shape=(4, 6), dtype=int32)


In [ ]:
# (4,6) -> (3,8) 형태로 reshape

tensor2 = tf.reshape(tensor1,[3,8])
print(tensor2)

# 행 인덱스 -1이 있는 경우 : 열을 기준으로 나누되, 행이 몇개가 되어도 상관없다는 의미
#   대신, 열의 인덱스 값은 지정이 되어 있어야..!
#   요소의 개수와 배열의 형태에 따라서 행의 크기가 알아서 결정됨

tf.Tensor(
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]], shape=(3, 8), dtype=int32)


In [ ]:
# (3, 8) -> (24, )

# tensor3 = tf.reshape(tensor2,[24,]) # 요소의 개수를 정확히 알고 있는 경우 사용해도 무방
tensor3 = tf.reshape(tensor2,[-1])    # 배열에 요소가 너무 많거나, 배열을 구성하고 있는 구조가 너무 복잡할 때 -1을 이용
print(tensor3)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,), dtype=int32)


In [ ]:
# (24, ) -> (2,3,4) 형태 (랭크-3텐서)

# tensor4 = tf.reshape(tensor3, [2,3,4])
tensor4 = tf.reshape(tensor3, [-1,3,4])
print(tensor4)

# 랭크 3개 중에 2개의 랭크가 (3,4)로 설정된 상태
# -1 위치느 자연스럽게 2가 나오게 되는 것
# 24 / (3 * 4) = 2

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)


In [ ]:
# 랭크-4 텐서 바꾸기
# (2,3,4) -> (2,2,3,2)

tensor5 = tf.reshape(tensor4, [2,2,3,-1])
print(tensor5)

tf.Tensor(
[[[[ 1  2]
   [ 3  4]
   [ 5  6]]

  [[ 7  8]
   [ 9 10]
   [11 12]]]


 [[[13 14]
   [15 16]
   [17 18]]

  [[19 20]
   [21 22]
   [23 24]]]], shape=(2, 2, 3, 2), dtype=int32)


# 변수 (tf.Variable)

Tensorflow : 계산처리 [그래프] 라는 객체를 구축 후, 그 그래프를 실행하는 것

변수 : 텐서플로를 활용해서 딥러닝 모델을 만들고, 학습을 시킬 때 정교한 연산을 제어하기 위해

변수에 담긴 값이 변할 가능성이 있음(바뀌어도 됨)

변수는 변화하는 학습률 값을 지정하는 그릇

In [ ]:
# (2,3)의 행렬 텐서 만들기
tensor = tf.constant([[10,20,30],
                      [40,50,60]])
print(tensor)

tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)


In [ ]:
# tensor를 Variable 함수에 입력 -> tensorflow의 변수가 생성

var1 = tf.Variable(tensor)  # tensor : 변수 초기값
# 변수 업데이트를 하면 초기값은 다른 값으로 변경될 수 있음
print(var1)

# 상수(tf.constant) : 값을 한 번 지정하면 변경할 수 없음
# 변수(tf.Variable) : 텐서 구조에 저장되어 있는 값이 변경될 수 있음

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60]], dtype=int32)>


In [ ]:
print(var1.name)
print(var1.shape)
print(var1.dtype)

Variable:0
(2, 3)
<dtype: 'int32'>


In [ ]:
# assing() 함수 : tensorflow변수에 새로운 데이터를 할당하는 함수
var1.assign([[100,200,300],
             [400,500,600]])

print(var1)

# ** 주의 ) 새로 입력하고자 하는 배열의 크기, 자료형이
#          원래 변수에 지정되어 있는 초기값의 배열크기, 자료형과 동일해야 한다.
# ex ) (2,3) 크기의 정수(int32)로 이루어진 변수 -> assign 함수 사용시에도 동일한 조건이어야 함

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[100, 200, 300],
       [400, 500, 600]], dtype=int32)>


In [ ]:
# tf.convert_to_tensor() : tensorflow 변수를 tensor로 변환
# ** 텐서로 변경하고 나면 텐서의 크기, 저장하고 있는 값 변경이 불가능 => 상수화가 된 것
tensor1 = tf.convert_to_tensor(var1)
print(tensor1)

tf.Tensor(
[[100 200 300]
 [400 500 600]], shape=(2, 3), dtype=int32)


In [ ]:
# tensor과 마찬가지로 tensorflow변수 역시 연산자 사용이 가능 O 
var1 + tensor1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 200,  400,  600],
       [ 800, 1000, 1200]], dtype=int32)>

In [ ]:
tf.__version__ # tensorflow 버전 확인하기

'2.8.0'

In [ ]:
# 상수 만들기

a = tf.constant(100)
b = tf.constant(10)

c = a + b

print(c)

tf.Tensor(110, shape=(), dtype=int32)


In [ ]:
import tensorflow.compat.v1 as tf      # 버전2에는 없는 기능을 사용하기 위해 버전1 가져옴
tf.compat.v1.disable_eager_execution() # 에러방지

# 상수 정의하기
a1 = tf.constant(10)
b1 = tf.constant(20)
c1 = tf.constant(30)

# 변수 정의하기
v = tf.Variable(0)

# 데이터 플로우 그래프 정의하기
r = a1 + b1 + c1
assign = tf.assign(v, r)

# session 실행하기
sess = tf.Session()
sess.run(assign)

# 변수 내용을 출력
print(sess.run(v))


60


# 플레이스홀더(placeholder)

딥러닝을 할 때 데이터 학습이 이루어져야만 함

이 학습을 진행할 때 학습할 데이터를 꼭 입력 해야 함

데이터를 입력받기 위해서 필요한 비어있는 변수

In [ ]:
# placeholder의 전달 parameter

# 실행 x
placeholder(
    dtype,          # dtype : data type, 필수기재
    shape=None,     # shape : 입력데이터의 형태(상수값 or 배열정보)
                    #         None으로 설정한 경우 어떠한 형태라도 들어갈 수 있다는 것을 의미
    name=None       # name  : 굳이 안해도 됨. 미기재시 None처리 됨
    )

In [ ]:
import tensorflow.compat.v1 as tf      # 버전2에는 없는 기능을 사용하기 위해 버전1 가져옴
tf.disable_v2_behavior()               # v2 사용 안하겠다.

ph1 = tf.placeholder(dtype=tf.float32)
ph2 = tf.placeholder(dtype=tf.float32)
ph3 = tf.placeholder(dtype=tf.float32)

rr = ph1 + ph2 + ph3

sess = tf.Session()
print(sess.run(rr,feed_dict={ph1:10, ph2:20, ph3:30}))
sess.close()

# placeholder는 다른 tensor를 할당하는 것 -> tensor를 매핑한다
# 할당을 위해서 사용하는 것 : feed_dict
print("---------------------")

arr1 = [1,2]
arr2 = [3,4]
arr3 = [5,6]

feed_dict = {ph1:arr1, ph2:arr2, ph3:arr3}

sess = tf.Session()
result1 = sess.run(rr, feed_dict=feed_dict)
print(result1)
sess.close()

60.0
---------------------
[ 9. 12.]


In [ ]:
# placeholder 정의
# 정수형 자료형을 가진 5개의 요소로 배열(list) 만들기
p = tf.placeholder(tf.int32, [5])

# 상수로 곱할 숫자 정의
n = tf.constant(3)

# 배열에 있는 모든 값에 상수 곱하는 연산 정의
# 데이터 플로우 그래프 정의
pn = p * n 

# 세션 시작하기
sess = tf.Session()

# 세션에 placeholder 값 넣고 실행
feed_dict = {p: [12,34,56,78,90]}
r2 = sess.run(pn, feed_dict=feed_dict)
print(r2)

[ 36 102 168 234 270]


In [ ]:
# placeholder 만들기 -> 배열 크기 정하지 않음
p1 = tf.placeholder(tf.int32, [None])
# 각 요소에 10배가 되는 식
n1 = tf.constant(10)
# 데이터 플로우 그래프 정의
pn1 = p1*n1
# 세션
sess = tf.Session()
# 계산한 결과
print(sess.run(pn1,feed_dict={p1:[2,4,6,9]}))

[20 40 60 90]


# tf.Variable vs tf.placeholder
* tf.Variable : 데이터의 상태를 저장하기 위해 사용
* tf.placeholder : 데이터를 입력하기 위해 사용